### ISSUE TITLE
Birdnet global 3k model misclassifies birds

### ISSUE THREAD

**Issue by MatthewBCooke** [MatthewBCooke/BirdNET-Pi-Debian#1]
**Describe the bug**
The new model randomly assigns species not native to my area

**To Reproduce**
1. Go to Tools>Settings
2. Click on 3K model > save settings > more info > species list previes
3. See if the list of species is appropriate

**Expected behavior**
Choosing the 3k model should update the species list appropriately and therefore classify species correctly

**Your build**
Debian 11 VM (on a TrueNAS Scale host with CPU passthrough). User: pi.

**Comment by MatthewBCooke** [comment]
https://github.com/mcguirepr89/BirdNET-Pi/discussions/251?sort=top#discussioncomment-5705263

**Comment by kobius77** [comment]
ok - continuing from [over there](https://github.com/mcguirepr89/BirdNET-Pi/discussions/251#discussioncomment-5835153) ..

i used the updater in the webinterface, switched back to the 6K model / english to wipe the slate clean and right after that back to 3K/german (which i actually want).

i can see in the syslog (and the file size/date of labels.txt) that now the file indeed is changed every time i switch.

the species list tester gives me proper results (but that it did before as well) - and looking at the log for a couple of minutes it seems to only show species from this list.

so it's looking good i guess. thanks.

**Comment by MatthewBCooke** [comment]
Yes testing this morning is only giving me accurate species. Thanks for the thorough reporting and troubleshooting!

**Comment by mattvdp** [comment]
Hi.  I did a fresh install today using your great instructions (and hard work in general) thanks MatthewBCooke.  

I can confirm that out of the box, using the default "BirdNET_6K_GLOBAL_MODEL (2020)" I was getting nonsense detections.

Switching to "BirdNET_GLOBAL_6K_V2.4_Model_FP16 (2023)" resolved the issue.
