### ISSUE TITLE
The installation exited unsuccessfully.

### ISSUE THREAD

**Issue by mnhn-paul** [MatthewBCooke/BirdNET-Pi-Debian#17]
**Describe the bug**
I'm unfortunately unable to install this on my proxmox instance, I´m getting an error, see below
**To Reproduce**
I followed you instruction on setting up a CT with debian 11 on my proxmox instance.
created the pi user and started `curl -s https://raw.githubusercontent.com/MatthewBCooke/BirdNET-Pi/debian/newinstaller.sh | bash`

**Screenshots**

![image](https://github.com/MatthewBCooke/BirdNET-Pi/assets/26623703/5f0fea90-ad2b-480a-bb34-32b9d8271dca)

this is the error message I'm getting:
```
remote: Total 145 (delta 10), reused 74 (delta 5), pack-reused 0
Receiving objects: 100% (145/145), 147.73 MiB | 18.69 MiB/s, done.
Resolving deltas: 100% (10/10), done.
+ exec
+++ date +%F
++ tee -i installation-2023-11-07.txt
tee: installation-2023-11-07.txt: Permission denied
+ set -e
+ my_dir=/home/pi/BirdNET-Pi
+ export my_dir=/home/pi/BirdNET-Pi
+ my_dir=/home/pi/BirdNET-Pi
+ cd /home/pi/BirdNET-Pi/scripts
++ uname -m
+ arch=x86_64
+ '[' x86_64 '!=' aarch64 ']'
+ '[' x86_64 '!=' x86_64 ']'
+ ./install_config.sh
+ set -e
+ trap 'exit 1' SIGINT SIGHUP
+ echo 'Beginning ./install_config.sh'
Beginning ./install_config.sh
+ birdnet_conf=/home/pi/BirdNET-Pi/birdnet.conf
++ curl -s4 http://ip-api.com/json
+ json=
+ exit 1
The installation exited unsuccessfully.
```

tryed with debian-11-standard_11-.6-1_amd6 and debian-11-standard_11-.7-1_amd6 

![image](https://github.com/MatthewBCooke/BirdNET-Pi/assets/26623703/b435622e-05ee-4036-b329-30165036b5ca)

Hope there is a solution for this, as I'm very much looking forward to using BirdNEtPi on a VM.

thanks in advance.

**Comment by mnhn-paul** [comment]
got the issue solved, piHole on my network was blocking something which was called during the installation...

**Comment by simongis** [comment]
@mnhn-paul - wanted to say thanks.  Exact same error, and exact same workaround.  I am not sure if I would have found that out so thank you.  Let me know if you had any other pihole challenges with the software running.
