### ISSUE TITLE
Depending on your VM setup, you might need to enable AVX/AVX2 instructions to avoid TensorFlow crashing with 'illegal instruction'

### ISSUE THREAD

**Issue by deepcoder** [MatthewBCooke/BirdNET-Pi-Debian#6]
Running a VM on Proxmox, not a LXC, VM's default instruction set does not include necessary CPU type to run Tensorflow as compiled.

/usr/local/bin/server.py does not start in systemctl after installation.

If you manually run : 
```
/home/pi/BirdNET-Pi/birdnet/bin/python3 /usr/local/bin/server.py
```
it stops with simply:
```
illegal instruction
```

Solution is to change the VM's CPU type from 'kvm' to 'host'. As long as your host CPU has these instructions (most likely) server.py will now run.

**Comment by Kickbut101** [comment]
Thank you!! I am having issues getting this to start recording with mic, and noticed that I also was getting "illegal instruction". This switch seems to have stopped that error
