### ISSUE TITLE
On 'Species Stats' tab : ModuleNotFoundError: No module named 'suntime'

### ISSUE THREAD

**Issue by deepcoder** [MatthewBCooke/BirdNET-Pi-Debian#7]
When trying to open 'Species Stats' tab:

```
ModuleNotFoundError: No module named 'suntime'
Traceback:


File "/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
File "/home/pi/BirdNET-Pi/scripts/plotly_streamlit.py", line 14, in <module>
    from suntime import Sun
```
suntime is not in the requirements.txt file.
tried to manually install:
```
sudo pip3 install suntime
```
this did NOT solve the problem after rebooting VM.

**Comment by MatthewBCooke** [comment]
Species stats works fine on my end (Debian VM with host-cpu passthrough). Tested on Truenas and XCP-NG. Did you follow the Proxmox setup guide?

**Comment by deepcoder** [comment]
This issue disappeared by itself, not sure as yet how. Might have been fixed by a standard update that BirdNET-Pi runs. I did not realize there was this updating feature in code until recently.

**Comment by simongis** [comment]
Just reporting in that on a fresh install on Debian 11, I am also encountering this issue:
 _No module named 'suntime'_

Can you elaborate on the 'updating feature' @deepcoder ?

![Image](https://github.com/user-attachments/assets/757923ee-9600-4c40-adda-a629bb4cfbf5)

**Comment by sfc-gh-vwalia** [comment]
Try this : 

$ cd /home/pi/BirdNET-Pi
$ . birdnet/bin/activate
(birdnet) $ pip install suntime
Collecting suntime
  Downloading suntime-1.3.2-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: python-dateutil in ./birdnet/lib/python3.9/site-packages (from suntime) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./birdnet/lib/python3.9/site-packages (from python-dateutil->suntime) (1.17.0)
Downloading suntime-1.3.2-py3-none-any.whl (7.2 kB)
Installing collected packages: suntime
Successfully installed suntime-1.3.2
(birdnet) $

**Comment by vikramwalia** [comment]
$ cd /home/pi/BirdNET-Pi
$ . birdnet/bin/activate
(birdnet) $ pip install suntime
Collecting suntime
  Downloading suntime-1.3.2-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: python-dateutil in ./birdnet/lib/python3.9/site-packages (from suntime) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./birdnet/lib/python3.9/site-packages (from python-dateutil->suntime) (1.17.0)
Downloading suntime-1.3.2-py3-none-any.whl (7.2 kB)
Installing collected packages: suntime
Successfully installed suntime-1.3.2
(birdnet) $
